#Install and Import Libraries

In [1]:
!pip install -qU langchain langchain-text-splitters langchain-community

In [2]:
# importing all libraries needed
import pandas as pd #for data processing
from langchain_text_splitters import CharacterTextSplitter, RecursiveCharacterTextSplitter #for splitter (chunking) method
from langchain_core.documents import Document #for langchain Document object

#Load dataset

In [3]:
#directory to dataset
data_path = "/content/drive/MyDrive/JCAIEAH-003/Notes and Hands On/Modul 3/Day 11/bbc-news-data.csv"

In [4]:
#read dataset with pandas
df = pd.read_csv(data_path, sep='\t')
print(df.shape) #show total row and column with format (row, column)
df.head() #show first 5 record of dataset

(2225, 4)

,category,filename,title,content
0,business,001.txt,Ad sales boost Time Warner profit,Quarterly profits at US media giant TimeWarne...
1,business,002.txt,Dollar gains on Greenspan speech,The dollar has hit its highest level against ...
2,business,003.txt,Yukos unit buyer faces loan claim,The owners of embattled Russian oil giant Yuk...
3,business,004.txt,High fuel prices hit BA's profits,British Airways has blamed high fuel prices f...
4,business,005.txt,Pernod takeover talk lifts Domecq,Shares in UK drinks and food firm Allied Dome...

In [5]:
df['category'].value_counts() #show category amount

category
sport            511
business         510
politics         417
tech             401
entertainment    386
Name: count, dtype: int64

In [6]:
#check characters amount is first news content
print(f"Amount of characters: {len(df.content[0])}")
#show the content
print(df.content[0])

Amount of characters: 2525
 Quarterly profits at US media giant TimeWarner jumped 76% to $1.13bn (£600m) for the three months to December, from $639m year-earlier.  The firm, which is now one of the biggest investors in Google, benefited from sales of high-speed internet connections and higher advert sales. TimeWarner said fourth quarter sales rose 2% to $11.1bn from $10.9bn. Its profits were buoyed by one-off gains which offset a profit dip at Warner Bros, and less users for AOL.  Time Warner said on Friday that it now owns 8% of search-engine Google. But its own internet business, AOL, had has mixed fortunes. It lost 464,000 subscribers in the fourth quarter profits were lower than in the preceding three quarters. However, the company said AOL's underlying profit before exceptional items rose 8% on the back of stronger internet advertising revenues. It hopes to increase subscribers by offering the online service free to TimeWarner internet customers and will try to sign up AOL's existing customers for high-speed broadband. TimeWarner also has to restate 2000 and 2003 results following a probe by the US Securities Exchange Commission (SEC), which is close to concluding.  Time Warner's fourth quarter profits were slightly better than analysts' expectations. But its film division saw profits slump 27% to $284m, helped by box-office flops Alexander and Catwoman, a sharp contrast to year-earlier, when the third and final film in the Lord of the Rings trilogy boosted results. For the full-year, TimeWarner posted a profit of $3.36bn, up 27% from its 2003 performance, while revenues grew 6.4% to $42.09bn. "Our financial performance was strong, meeting or exceeding all of our full-year objectives and greatly enhancing our flexibility," chairman and chief executive Richard Parsons said. For 2005, TimeWarner is projecting operating earnings growth of around 5%, and also expects higher revenue and wider profit margins.  TimeWarner is to restate its accounts as part of efforts to resolve an inquiry into AOL by US market regulators. It has already offered to pay $300m to settle charges, in a deal that is under review by the SEC. The company said it was unable to estimate the amount it needed to set aside for legal reserves, which it previously set at $500m. It intends to adjust the way it accounts for a deal with German music publisher Bertelsmann's purchase of a stake in AOL Europe, which it had reported as advertising revenue. It will now book the sale of its stake in AOL Europe as a loss on the value of that stake.

#Chunking

In [8]:
#fixed size chunking
character_size = 101 #each chunk contains 101 characters
char_count=0 #character counter for while loop incremental
selected_content = df.content[0] #select a news content from dataset
while char_count < len(df.content[0]):
  print(selected_content[char_count:char_count+character_size])
  print("=======================================================================================================================")
  char_count += character_size

 Quarterly profits at US media giant TimeWarner jumped 76% to $1.13bn (£600m) for the three months to
=======================================================================================================================
 December, from $639m year-earlier.  The firm, which is now one of the biggest investors in Google, b
=======================================================================================================================
enefited from sales of high-speed internet connections and higher advert sales. TimeWarner said fourt
=======================================================================================================================
h quarter sales rose 2% to $11.1bn from $10.9bn. Its profits were buoyed by one-off gains which offse
=======================================================================================================================
t a profit dip at Warner Bros, and less users for AOL.  Time Warner said on Friday that it now owns 8
=======================================================================================================================
% of search-engine Google. But its own internet business, AOL, had has mixed fortunes. It lost 464,00
=======================================================================================================================
0 subscribers in the fourth quarter profits were lower than in the preceding three quarters. However,
=======================================================================================================================
 the company said AOL's underlying profit before exceptional items rose 8% on the back of stronger in
=======================================================================================================================
ternet advertising revenues. It hopes to increase subscribers by offering the online service free to
=======================================================================================================================
TimeWarner internet customers and will try to sign up AOL's existing customers for high-speed broadba
=======================================================================================================================
nd. TimeWarner also has to restate 2000 and 2003 results following a probe by the US Securities Excha
=======================================================================================================================
nge Commission (SEC), which is close to concluding.  Time Warner's fourth quarter profits were slight
=======================================================================================================================
ly better than analysts' expectations. But its film division saw profits slump 27% to $284m, helped b
=======================================================================================================================
y box-office flops Alexander and Catwoman, a sharp contrast to year-earlier, when the third and final
=======================================================================================================================
 film in the Lord of the Rings trilogy boosted results. For the full-year, TimeWarner posted a profit
=======================================================================================================================
 of $3.36bn, up 27% from its 2003 performance, while revenues grew 6.4% to $42.09bn. "Our financial p
=======================================================================================================================
erformance was strong, meeting or exceeding all of our full-year objectives and greatly enhancing our
=======================================================================================================================
 flexibility," chairman and chief executive Richard Parsons said. For 2005, TimeWarner is projecting
=======================================================================================================================
operating earnings growth of around 5%, and also expects higher revenue and wider profit margins.  Ti
=======================================================================================================================
meWarner is to restate its accounts as part of efforts to resolve an inquiry into AOL by US market re
=======================================================================================================================
gulators. It has already offered to pay $300m to settle charges, in a deal that is under review by th
=======================================================================================================================
e SEC. The company said it was unable to estimate the amount it needed to set aside for legal reserve
=======================================================================================================================
s, which it previously set at $500m. It intends to adjust the way it accounts for a deal with German
=======================================================================================================================
music publisher Bertelsmann's purchase of a stake in AOL Europe, which it had reported as advertising
=======================================================================================================================
 revenue. It will now book the sale of its stake in AOL Europe as a loss on the value of that stake.
=======================================================================================================================

In [9]:
# store to langchain Document object
character_size = 101 #each chunk contains 101 characters
char_count=0 #character counter for while loop incremental
selected_content = df.content[0] #select a news content from dataset
while char_count < len(df.content[0]):
  print(Document(page_content=selected_content[char_count:char_count+character_size]))
  char_count += character_size

page_content=' Quarterly profits at US media giant TimeWarner jumped 76% to $1.13bn (£600m) for the three months to'
page_content=' December, from $639m year-earlier.  The firm, which is now one of the biggest investors in Google, b'
page_content='enefited from sales of high-speed internet connections and higher advert sales. TimeWarner said fourt'
page_content='h quarter sales rose 2% to $11.1bn from $10.9bn. Its profits were buoyed by one-off gains which offse'
page_content='t a profit dip at Warner Bros, and less users for AOL.  Time Warner said on Friday that it now owns 8'
page_content='% of search-engine Google. But its own internet business, AOL, had has mixed fortunes. It lost 464,00'
page_content='0 subscribers in the fourth quarter profits were lower than in the preceding three quarters. However,'
page_content=' the company said AOL's underlying profit before exceptional items rose 8% on the back of stronger in'
page_content='ternet advertising revenues. It hopes to increase subscribers by offering the online service free to '
page_content='TimeWarner internet customers and will try to sign up AOL's existing customers for high-speed broadba'
page_content='nd. TimeWarner also has to restate 2000 and 2003 results following a probe by the US Securities Excha'
page_content='nge Commission (SEC), which is close to concluding.  Time Warner's fourth quarter profits were slight'
page_content='ly better than analysts' expectations. But its film division saw profits slump 27% to $284m, helped b'
page_content='y box-office flops Alexander and Catwoman, a sharp contrast to year-earlier, when the third and final'
page_content=' film in the Lord of the Rings trilogy boosted results. For the full-year, TimeWarner posted a profit'
page_content=' of $3.36bn, up 27% from its 2003 performance, while revenues grew 6.4% to $42.09bn. "Our financial p'
page_content='erformance was strong, meeting or exceeding all of our full-year objectives and greatly enhancing our'
page_content=' flexibility," chairman and chief executive Richard Parsons said. For 2005, TimeWarner is projecting '
page_content='operating earnings growth of around 5%, and also expects higher revenue and wider profit margins.  Ti'
page_content='meWarner is to restate its accounts as part of efforts to resolve an inquiry into AOL by US market re'
page_content='gulators. It has already offered to pay $300m to settle charges, in a deal that is under review by th'
page_content='e SEC. The company said it was unable to estimate the amount it needed to set aside for legal reserve'
page_content='s, which it previously set at $500m. It intends to adjust the way it accounts for a deal with German '
page_content='music publisher Bertelsmann's purchase of a stake in AOL Europe, which it had reported as advertising'
page_content=' revenue. It will now book the sale of its stake in AOL Europe as a loss on the value of that stake. '

In [10]:
#chunk text with CharacterTextSplitter
#separator: " " (space)
#chunk size: 101 characters
#chunk overlap: 10 (current chunk will bring last 10 characters from previous chunk)
splitter = CharacterTextSplitter(
    separator=" ",
    chunk_size=101,
    chunk_overlap=10,
)

In [11]:
splitter.split_text(selected_content)

['Quarterly profits at US media giant TimeWarner jumped 76% to $1.13bn (£600m) for the three months to',
 'months to December, from $639m year-earlier. The firm, which is now one of the biggest investors in',
 'in Google, benefited from sales of high-speed internet connections and higher advert sales.',
 'sales. TimeWarner said fourth quarter sales rose 2% to $11.1bn from $10.9bn. Its profits were buoyed',
 'buoyed by one-off gains which offset a profit dip at Warner Bros, and less users for AOL. Time Warner',
 'Warner said on Friday that it now owns 8% of search-engine Google. But its own internet business,',
 'business, AOL, had has mixed fortunes. It lost 464,000 subscribers in the fourth quarter profits were',
 "were lower than in the preceding three quarters. However, the company said AOL's underlying profit",
 'profit before exceptional items rose 8% on the back of stronger internet advertising revenues. It',
 'It hopes to increase subscribers by offering the online service free to TimeWarner internet customers',
 "customers and will try to sign up AOL's existing customers for high-speed broadband. TimeWarner also",
 'also has to restate 2000 and 2003 results following a probe by the US Securities Exchange Commission',
 "Commission (SEC), which is close to concluding. Time Warner's fourth quarter profits were slightly",
 "slightly better than analysts' expectations. But its film division saw profits slump 27% to $284m,",
 'to $284m, helped by box-office flops Alexander and Catwoman, a sharp contrast to year-earlier, when',
 'when the third and final film in the Lord of the Rings trilogy boosted results. For the full-year,',
 'full-year, TimeWarner posted a profit of $3.36bn, up 27% from its 2003 performance, while revenues',
 'revenues grew 6.4% to $42.09bn. "Our financial performance was strong, meeting or exceeding all of',
 'all of our full-year objectives and greatly enhancing our flexibility," chairman and chief executive',
 'executive Richard Parsons said. For 2005, TimeWarner is projecting operating earnings growth of',
 'growth of around 5%, and also expects higher revenue and wider profit margins. TimeWarner is to',
 'is to restate its accounts as part of efforts to resolve an inquiry into AOL by US market regulators.',
 'It has already offered to pay $300m to settle charges, in a deal that is under review by the SEC. The',
 'SEC. The company said it was unable to estimate the amount it needed to set aside for legal reserves,',
 'reserves, which it previously set at $500m. It intends to adjust the way it accounts for a deal with',
 "deal with German music publisher Bertelsmann's purchase of a stake in AOL Europe, which it had",
 'it had reported as advertising revenue. It will now book the sale of its stake in AOL Europe as a',
 'as a loss on the value of that stake.']

In [12]:
#split the text and transform into langchain Document object
splitter.create_documents([selected_content])

[Document(metadata={}, page_content='Quarterly profits at US media giant TimeWarner jumped 76% to $1.13bn (£600m) for the three months to'),
 Document(metadata={}, page_content='months to December, from $639m year-earlier. The firm, which is now one of the biggest investors in'),
 Document(metadata={}, page_content='in Google, benefited from sales of high-speed internet connections and higher advert sales.'),
 Document(metadata={}, page_content='sales. TimeWarner said fourth quarter sales rose 2% to $11.1bn from $10.9bn. Its profits were buoyed'),
 Document(metadata={}, page_content='buoyed by one-off gains which offset a profit dip at Warner Bros, and less users for AOL. Time Warner'),
 Document(metadata={}, page_content='Warner said on Friday that it now owns 8% of search-engine Google. But its own internet business,'),
 Document(metadata={}, page_content='business, AOL, had has mixed fortunes. It lost 464,000 subscribers in the fourth quarter profits were'),
 Document(metadata={}, page_content="were lower than in the preceding three quarters. However, the company said AOL's underlying profit"),
 Document(metadata={}, page_content='profit before exceptional items rose 8% on the back of stronger internet advertising revenues. It'),
 Document(metadata={}, page_content='It hopes to increase subscribers by offering the online service free to TimeWarner internet customers'),
 Document(metadata={}, page_content="customers and will try to sign up AOL's existing customers for high-speed broadband. TimeWarner also"),
 Document(metadata={}, page_content='also has to restate 2000 and 2003 results following a probe by the US Securities Exchange Commission'),
 Document(metadata={}, page_content="Commission (SEC), which is close to concluding. Time Warner's fourth quarter profits were slightly"),
 Document(metadata={}, page_content="slightly better than analysts' expectations. But its film division saw profits slump 27% to $284m,"),
 Document(metadata={}, page_content='to $284m, helped by box-office flops Alexander and Catwoman, a sharp contrast to year-earlier, when'),
 Document(metadata={}, page_content='when the third and final film in the Lord of the Rings trilogy boosted results. For the full-year,'),
 Document(metadata={}, page_content='full-year, TimeWarner posted a profit of $3.36bn, up 27% from its 2003 performance, while revenues'),
 Document(metadata={}, page_content='revenues grew 6.4% to $42.09bn. "Our financial performance was strong, meeting or exceeding all of'),
 Document(metadata={}, page_content='all of our full-year objectives and greatly enhancing our flexibility," chairman and chief executive'),
 Document(metadata={}, page_content='executive Richard Parsons said. For 2005, TimeWarner is projecting operating earnings growth of'),
 Document(metadata={}, page_content='growth of around 5%, and also expects higher revenue and wider profit margins. TimeWarner is to'),
 Document(metadata={}, page_content='is to restate its accounts as part of efforts to resolve an inquiry into AOL by US market regulators.'),
 Document(metadata={}, page_content='It has already offered to pay $300m to settle charges, in a deal that is under review by the SEC. The'),
 Document(metadata={}, page_content='SEC. The company said it was unable to estimate the amount it needed to set aside for legal reserves,'),
 Document(metadata={}, page_content='reserves, which it previously set at $500m. It intends to adjust the way it accounts for a deal with'),
 Document(metadata={}, page_content="deal with German music publisher Bertelsmann's purchase of a stake in AOL Europe, which it had"),
 Document(metadata={}, page_content='it had reported as advertising revenue. It will now book the sale of its stake in AOL Europe as a'),
 Document(metadata={}, page_content='as a loss on the value of that stake.')]

In [14]:
#chunk text with CharacterTextSplitter
#separators: [" ", "."] (space, dot)
#chunk size: 101 characters
#chunk overlap: 10 (current chunk will bring last 10 characters from previous chunk)
splitter = RecursiveCharacterTextSplitter(
    separators=[" ", "."],
    chunk_size=101,
    chunk_overlap=10,
)

In [15]:
#split the text
splitter.split_text(selected_content)

['Quarterly profits at US media giant TimeWarner jumped 76% to $1.13bn (£600m) for the three months to',
 'months to December, from $639m year-earlier.  The firm, which is now one of the biggest investors in',
 'in Google, benefited from sales of high-speed internet connections and higher advert sales.',
 'sales. TimeWarner said fourth quarter sales rose 2% to $11.1bn from $10.9bn. Its profits were buoyed',
 'buoyed by one-off gains which offset a profit dip at Warner Bros, and less users for AOL.  Time',
 'Time Warner said on Friday that it now owns 8% of search-engine Google. But its own internet',
 'internet business, AOL, had has mixed fortunes. It lost 464,000 subscribers in the fourth quarter',
 "quarter profits were lower than in the preceding three quarters. However, the company said AOL's",
 "AOL's underlying profit before exceptional items rose 8% on the back of stronger internet",
 'internet advertising revenues. It hopes to increase subscribers by offering the online service free',
 "free to TimeWarner internet customers and will try to sign up AOL's existing customers for",
 'for high-speed broadband. TimeWarner also has to restate 2000 and 2003 results following a probe by',
 "probe by the US Securities Exchange Commission (SEC), which is close to concluding.  Time Warner's",
 "Warner's fourth quarter profits were slightly better than analysts' expectations. But its film",
 'its film division saw profits slump 27% to $284m, helped by box-office flops Alexander and Catwoman,',
 'Catwoman, a sharp contrast to year-earlier, when the third and final film in the Lord of the Rings',
 'the Rings trilogy boosted results. For the full-year, TimeWarner posted a profit of $3.36bn, up 27%',
 'up 27% from its 2003 performance, while revenues grew 6.4% to $42.09bn. "Our financial performance',
 'was strong, meeting or exceeding all of our full-year objectives and greatly enhancing our',
 'our flexibility," chairman and chief executive Richard Parsons said. For 2005, TimeWarner is',
 'is projecting operating earnings growth of around 5%, and also expects higher revenue and wider',
 'and wider profit margins.  TimeWarner is to restate its accounts as part of efforts to resolve an',
 'an inquiry into AOL by US market regulators. It has already offered to pay $300m to settle charges,',
 'charges, in a deal that is under review by the SEC. The company said it was unable to estimate the',
 'the amount it needed to set aside for legal reserves, which it previously set at $500m. It intends',
 "intends to adjust the way it accounts for a deal with German music publisher Bertelsmann's purchase",
 'purchase of a stake in AOL Europe, which it had reported as advertising revenue. It will now book',
 'now book the sale of its stake in AOL Europe as a loss on the value of that stake.']

In [16]:
#split the text and transform into langchain Document object
splitter.create_documents([selected_content])

[Document(metadata={}, page_content='Quarterly profits at US media giant TimeWarner jumped 76% to $1.13bn (£600m) for the three months to'),
 Document(metadata={}, page_content='months to December, from $639m year-earlier.  The firm, which is now one of the biggest investors in'),
 Document(metadata={}, page_content='in Google, benefited from sales of high-speed internet connections and higher advert sales.'),
 Document(metadata={}, page_content='sales. TimeWarner said fourth quarter sales rose 2% to $11.1bn from $10.9bn. Its profits were buoyed'),
 Document(metadata={}, page_content='buoyed by one-off gains which offset a profit dip at Warner Bros, and less users for AOL.  Time'),
 Document(metadata={}, page_content='Time Warner said on Friday that it now owns 8% of search-engine Google. But its own internet'),
 Document(metadata={}, page_content='internet business, AOL, had has mixed fortunes. It lost 464,000 subscribers in the fourth quarter'),
 Document(metadata={}, page_content="quarter profits were lower than in the preceding three quarters. However, the company said AOL's"),
 Document(metadata={}, page_content="AOL's underlying profit before exceptional items rose 8% on the back of stronger internet"),
 Document(metadata={}, page_content='internet advertising revenues. It hopes to increase subscribers by offering the online service free'),
 Document(metadata={}, page_content="free to TimeWarner internet customers and will try to sign up AOL's existing customers for"),
 Document(metadata={}, page_content='for high-speed broadband. TimeWarner also has to restate 2000 and 2003 results following a probe by'),
 Document(metadata={}, page_content="probe by the US Securities Exchange Commission (SEC), which is close to concluding.  Time Warner's"),
 Document(metadata={}, page_content="Warner's fourth quarter profits were slightly better than analysts' expectations. But its film"),
 Document(metadata={}, page_content='its film division saw profits slump 27% to $284m, helped by box-office flops Alexander and Catwoman,'),
 Document(metadata={}, page_content='Catwoman, a sharp contrast to year-earlier, when the third and final film in the Lord of the Rings'),
 Document(metadata={}, page_content='the Rings trilogy boosted results. For the full-year, TimeWarner posted a profit of $3.36bn, up 27%'),
 Document(metadata={}, page_content='up 27% from its 2003 performance, while revenues grew 6.4% to $42.09bn. "Our financial performance'),
 Document(metadata={}, page_content='was strong, meeting or exceeding all of our full-year objectives and greatly enhancing our'),
 Document(metadata={}, page_content='our flexibility," chairman and chief executive Richard Parsons said. For 2005, TimeWarner is'),
 Document(metadata={}, page_content='is projecting operating earnings growth of around 5%, and also expects higher revenue and wider'),
 Document(metadata={}, page_content='and wider profit margins.  TimeWarner is to restate its accounts as part of efforts to resolve an'),
 Document(metadata={}, page_content='an inquiry into AOL by US market regulators. It has already offered to pay $300m to settle charges,'),
 Document(metadata={}, page_content='charges, in a deal that is under review by the SEC. The company said it was unable to estimate the'),
 Document(metadata={}, page_content='the amount it needed to set aside for legal reserves, which it previously set at $500m. It intends'),
 Document(metadata={}, page_content="intends to adjust the way it accounts for a deal with German music publisher Bertelsmann's purchase"),
 Document(metadata={}, page_content='purchase of a stake in AOL Europe, which it had reported as advertising revenue. It will now book'),
 Document(metadata={}, page_content='now book the sale of its stake in AOL Europe as a loss on the value of that stake.')]