# Series and Dataframe

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Series from list
mydata = [0,1,2,3,4]
pd.Series(mydata)

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [3]:
# Series from numpy array
mydata = np.array([0,2,3,4,5,7])
pd.Series(data=mydata)

0    0
1    2
2    3
3    4
4    5
5    7
dtype: int64

In [4]:
sample = {
    'a':10,
    'b':20,
    'c':30
}
pd.Series(sample)

a    10
b    20
c    30
dtype: int64

In [5]:
# Dataframe from list
sample = [[1,2,3], [4,5,6], [7,8,9]]
pd.DataFrame(sample)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [6]:
sample = [[1,2,3], [4,5,6], [7,8,9]]
pd.DataFrame(data=sample, columns=["tinggi_badan", "berat_badan", "usia"])

   tinggi_badan  berat_badan  usia
0             1            2     3
1             4            5     6
2             7            8     9

In [7]:
# Dataframe from numpy array
sample = np.random.randn(5,4)
pd.DataFrame(sample)

          0         1         2         3
0 -1.390394 -1.379772 -0.311613 -0.644885
1  0.333364  0.472487 -0.001804 -0.482947
2  0.018627  1.472745 -0.901832  1.734962
3 -0.080476  0.318781 -1.502729 -0.158983
4  0.260598 -0.426645  0.423670 -0.588081

In [8]:
# Dataframe from dict
sampel = {
    'a': [1,2,3],
    'b': [4,5,6],
}
pd.DataFrame(sampel)

   a  b
0  1  4
1  2  5
2  3  6

In [9]:
# catatan tambahan
# function .split()

text = "Saya belajar bahasa pemrograman Python di Purwadhika."
text.split()

['Saya', 'belajar', 'bahasa', 'pemrograman', 'Python', 'di', 'Purwadhika.']

In [10]:
kumpulan_kata = text.split()
kumpulan_kata[2]

'bahasa'

In [11]:
text = "Saya suka makan apel, mangga, pisang, jeruk, dan semangka"
text.split(",")

['Saya suka makan apel', ' mangga', ' pisang', ' jeruk', ' dan semangka']

In [12]:
text = 'W X Y Z'
text.split()

['W', 'X', 'Y', 'Z']

# Selection and Indexing

In [13]:
sample = np.random.randn(5,4)
df = pd.DataFrame(sample, columns=["tinggi_badan", "berat badan", "usia", "penghasilan"])
df

   tinggi_badan  berat badan      usia  penghasilan
0      1.245234    -0.960152 -0.780492     0.178042
1      0.725512     0.101368  0.995391    -0.356335
2      0.970489     0.319889  0.410704     0.077164
3     -2.176524     1.053369 -0.095821    -0.426086
4     -1.262593     0.052173  0.788016    -0.506023

In [14]:
# selecting a column
df.tinggi_badan

0    1.245234
1    0.725512
2    0.970489
3   -2.176524
4   -1.262593
Name: tinggi_badan, dtype: float64

In [15]:
df["berat badan"]

0   -0.960152
1    0.101368
2    0.319889
3    1.053369
4    0.052173
Name: berat badan, dtype: float64

In [16]:
# Accessing data by index
df['tinggi_badan'][0]

np.float64(1.2452340647525175)

In [17]:
# Accessing range in column
df['tinggi_badan'][2:]

2    0.970489
3   -2.176524
4   -1.262593
Name: tinggi_badan, dtype: float64

In [18]:
# Accessing 2 or more columns
df[['tinggi_badan', 'usia']]

   tinggi_badan      usia
0      1.245234 -0.780492
1      0.725512  0.995391
2      0.970489  0.410704
3     -2.176524 -0.095821
4     -1.262593  0.788016

In [19]:
df = pd.DataFrame(sample, columns=["tinggi_badan", "berat badan", "usia", "penghasilan"], index=['a','b','c','d','e'])
df

   tinggi_badan  berat badan      usia  penghasilan
a      1.245234    -0.960152 -0.780492     0.178042
b      0.725512     0.101368  0.995391    -0.356335
c      0.970489     0.319889  0.410704     0.077164
d     -2.176524     1.053369 -0.095821    -0.426086
e     -1.262593     0.052173  0.788016    -0.506023

## loc and iloc

In [20]:
# loc
df.loc['a']

tinggi_badan    1.245234
berat badan    -0.960152
usia           -0.780492
penghasilan     0.178042
Name: a, dtype: float64

In [21]:
df.loc['a':'c']

   tinggi_badan  berat badan      usia  penghasilan
a      1.245234    -0.960152 -0.780492     0.178042
b      0.725512     0.101368  0.995391    -0.356335
c      0.970489     0.319889  0.410704     0.077164

In [22]:
# iloc
df.iloc[0,2]

np.float64(-0.780491814559277)

In [23]:
df.iloc[0:3, 3:]

   penghasilan
a     0.178042
b    -0.356335
c     0.077164

In [24]:
df.iloc[2]

tinggi_badan    0.970489
berat badan     0.319889
usia            0.410704
penghasilan     0.077164
Name: c, dtype: float64

In [25]:
df.iloc[2:4]

   tinggi_badan  berat badan      usia  penghasilan
c      0.970489     0.319889  0.410704     0.077164
d     -2.176524     1.053369 -0.095821    -0.426086

In [26]:
df.iloc[0:6:2]

   tinggi_badan  berat badan      usia  penghasilan
a      1.245234    -0.960152 -0.780492     0.178042
c      0.970489     0.319889  0.410704     0.077164
e     -1.262593     0.052173  0.788016    -0.506023

In [27]:
df.iloc[[1,4]]

   tinggi_badan  berat badan      usia  penghasilan
b      0.725512     0.101368  0.995391    -0.356335
e     -1.262593     0.052173  0.788016    -0.506023

## conditional selection

In [28]:
sample = np.random.randn(10,4)
df = pd.DataFrame(sample, columns=["W", "X", "Y", "Z"])
df

          W         X         Y         Z
0 -1.332414 -0.314573 -1.241171  0.305037
1  1.826389  0.381645  0.485832 -1.053713
2  0.197861  0.974430  0.120439  0.365430
3 -0.902754  1.407560  0.005022  1.216367
4  0.631168  1.469964 -1.399771  0.660876
5 -0.153109  0.341167 -0.859981 -1.057574
6  0.695961  0.457311  0.570612 -1.168058
7 -1.156498  0.703419 -0.270342  0.425816
8 -0.774539  0.140517 -0.249065  0.640874
9  0.540935 -0.789033 -0.657223  0.558372

In [29]:
# conditional selection by dataframe
df[df>0]

          W         X         Y         Z
0       NaN       NaN       NaN  0.305037
1  1.826389  0.381645  0.485832       NaN
2  0.197861  0.974430  0.120439  0.365430
3       NaN  1.407560  0.005022  1.216367
4  0.631168  1.469964       NaN  0.660876
5       NaN  0.341167       NaN       NaN
6  0.695961  0.457311  0.570612       NaN
7       NaN  0.703419       NaN  0.425816
8       NaN  0.140517       NaN  0.640874
9  0.540935       NaN       NaN  0.558372

In [30]:
# conditional selection by columns
df[df['W']>0]

          W         X         Y         Z
1  1.826389  0.381645  0.485832 -1.053713
2  0.197861  0.974430  0.120439  0.365430
4  0.631168  1.469964 -1.399771  0.660876
6  0.695961  0.457311  0.570612 -1.168058
9  0.540935 -0.789033 -0.657223  0.558372

In [31]:
df[df['W']>0][['Y','Z']]

          Y         Z
1  0.485832 -1.053713
2  0.120439  0.365430
4 -1.399771  0.660876
6  0.570612 -1.168058
9 -0.657223  0.558372

In [32]:
# multiple condition selection
df[(df['W']>0) & (df['Y']>0)]

          W         X         Y         Z
1  1.826389  0.381645  0.485832 -1.053713
2  0.197861  0.974430  0.120439  0.365430
6  0.695961  0.457311  0.570612 -1.168058

In [33]:
employee = {
    'name': ['John Wick', 'Jane Stone', 'Jack Sparrow', 'Jill Smith'],
    'gender': ['M', 'F', 'M', 'F'],
    'hire_date': ['2020-01-01', '2020-02-01', '2020-03-01', '2020-04-01'],
    'salary': [500, 600, 700, 800]
}
df = pd.DataFrame(employee)
df

           name gender   hire_date  salary
0     John Wick      M  2020-01-01     500
1    Jane Stone      F  2020-02-01     600
2  Jack Sparrow      M  2020-03-01     700
3    Jill Smith      F  2020-04-01     800

In [34]:
df[df['name'] == 'John Wick']

        name gender   hire_date  salary
0  John Wick      M  2020-01-01     500

# Manipulating Data

In [35]:
sample = np.random.randn(10,4)
df = pd.DataFrame(sample, columns=["W", "X", "Y", "Z"])
df

          W         X         Y         Z
0 -1.076477 -0.570194 -0.983457  0.695465
1 -1.011685  0.287847  0.353124  1.609088
2 -0.061852  0.407979  2.675069  0.139342
3  1.582947 -0.634168 -0.476795 -1.758901
4  0.354699  0.205733  1.064277  0.321967
5  1.062526 -0.328039 -0.091156  0.373162
6  0.379371  0.877800 -0.828435  0.010890
7  1.570932 -0.300051 -0.148241  0.212808
8  0.146590  1.377085 -1.187127  0.371938
9 -1.466572 -0.431312  0.035870 -0.307462

In [36]:
df['new'] = df['W'] + df['X']
df

          W         X         Y         Z       new
0 -1.076477 -0.570194 -0.983457  0.695465 -1.646671
1 -1.011685  0.287847  0.353124  1.609088 -0.723838
2 -0.061852  0.407979  2.675069  0.139342  0.346127
3  1.582947 -0.634168 -0.476795 -1.758901  0.948779
4  0.354699  0.205733  1.064277  0.321967  0.560432
5  1.062526 -0.328039 -0.091156  0.373162  0.734487
6  0.379371  0.877800 -0.828435  0.010890  1.257171
7  1.570932 -0.300051 -0.148241  0.212808  1.270881
8  0.146590  1.377085 -1.187127  0.371938  1.523676
9 -1.466572 -0.431312  0.035870 -0.307462 -1.897884

In [37]:
df.drop('new', axis=1)

          W         X         Y         Z
0 -1.076477 -0.570194 -0.983457  0.695465
1 -1.011685  0.287847  0.353124  1.609088
2 -0.061852  0.407979  2.675069  0.139342
3  1.582947 -0.634168 -0.476795 -1.758901
4  0.354699  0.205733  1.064277  0.321967
5  1.062526 -0.328039 -0.091156  0.373162
6  0.379371  0.877800 -0.828435  0.010890
7  1.570932 -0.300051 -0.148241  0.212808
8  0.146590  1.377085 -1.187127  0.371938
9 -1.466572 -0.431312  0.035870 -0.307462

In [38]:
df

          W         X         Y         Z       new
0 -1.076477 -0.570194 -0.983457  0.695465 -1.646671
1 -1.011685  0.287847  0.353124  1.609088 -0.723838
2 -0.061852  0.407979  2.675069  0.139342  0.346127
3  1.582947 -0.634168 -0.476795 -1.758901  0.948779
4  0.354699  0.205733  1.064277  0.321967  0.560432
5  1.062526 -0.328039 -0.091156  0.373162  0.734487
6  0.379371  0.877800 -0.828435  0.010890  1.257171
7  1.570932 -0.300051 -0.148241  0.212808  1.270881
8  0.146590  1.377085 -1.187127  0.371938  1.523676
9 -1.466572 -0.431312  0.035870 -0.307462 -1.897884

In [39]:
df1 = df.drop('new', axis=1)
df1

          W         X         Y         Z
0 -1.076477 -0.570194 -0.983457  0.695465
1 -1.011685  0.287847  0.353124  1.609088
2 -0.061852  0.407979  2.675069  0.139342
3  1.582947 -0.634168 -0.476795 -1.758901
4  0.354699  0.205733  1.064277  0.321967
5  1.062526 -0.328039 -0.091156  0.373162
6  0.379371  0.877800 -0.828435  0.010890
7  1.570932 -0.300051 -0.148241  0.212808
8  0.146590  1.377085 -1.187127  0.371938
9 -1.466572 -0.431312  0.035870 -0.307462

In [40]:
df.drop('new', axis=1, inplace=True)

In [41]:
df

          W         X         Y         Z
0 -1.076477 -0.570194 -0.983457  0.695465
1 -1.011685  0.287847  0.353124  1.609088
2 -0.061852  0.407979  2.675069  0.139342
3  1.582947 -0.634168 -0.476795 -1.758901
4  0.354699  0.205733  1.064277  0.321967
5  1.062526 -0.328039 -0.091156  0.373162
6  0.379371  0.877800 -0.828435  0.010890
7  1.570932 -0.300051 -0.148241  0.212808
8  0.146590  1.377085 -1.187127  0.371938
9 -1.466572 -0.431312  0.035870 -0.307462

In [42]:
# delete row
df.drop(3, axis=0)

          W         X         Y         Z
0 -1.076477 -0.570194 -0.983457  0.695465
1 -1.011685  0.287847  0.353124  1.609088
2 -0.061852  0.407979  2.675069  0.139342
4  0.354699  0.205733  1.064277  0.321967
5  1.062526 -0.328039 -0.091156  0.373162
6  0.379371  0.877800 -0.828435  0.010890
7  1.570932 -0.300051 -0.148241  0.212808
8  0.146590  1.377085 -1.187127  0.371938
9 -1.466572 -0.431312  0.035870 -0.307462

In [43]:
df

          W         X         Y         Z
0 -1.076477 -0.570194 -0.983457  0.695465
1 -1.011685  0.287847  0.353124  1.609088
2 -0.061852  0.407979  2.675069  0.139342
3  1.582947 -0.634168 -0.476795 -1.758901
4  0.354699  0.205733  1.064277  0.321967
5  1.062526 -0.328039 -0.091156  0.373162
6  0.379371  0.877800 -0.828435  0.010890
7  1.570932 -0.300051 -0.148241  0.212808
8  0.146590  1.377085 -1.187127  0.371938
9 -1.466572 -0.431312  0.035870 -0.307462

## More about Index

In [44]:
df

          W         X         Y         Z
0 -1.076477 -0.570194 -0.983457  0.695465
1 -1.011685  0.287847  0.353124  1.609088
2 -0.061852  0.407979  2.675069  0.139342
3  1.582947 -0.634168 -0.476795 -1.758901
4  0.354699  0.205733  1.064277  0.321967
5  1.062526 -0.328039 -0.091156  0.373162
6  0.379371  0.877800 -0.828435  0.010890
7  1.570932 -0.300051 -0.148241  0.212808
8  0.146590  1.377085 -1.187127  0.371938
9 -1.466572 -0.431312  0.035870 -0.307462

In [46]:
df['city'] = ['Jakarta', 'Bandung', 'Surabaya', 'Medan', 'Jogja', 'Lampung', 'Balikpapan', 'Makassar', 'Semarang', 'Denpasar']
df

          W         X         Y         Z        city
0 -1.076477 -0.570194 -0.983457  0.695465     Jakarta
1 -1.011685  0.287847  0.353124  1.609088     Bandung
2 -0.061852  0.407979  2.675069  0.139342    Surabaya
3  1.582947 -0.634168 -0.476795 -1.758901       Medan
4  0.354699  0.205733  1.064277  0.321967       Jogja
5  1.062526 -0.328039 -0.091156  0.373162     Lampung
6  0.379371  0.877800 -0.828435  0.010890  Balikpapan
7  1.570932 -0.300051 -0.148241  0.212808    Makassar
8  0.146590  1.377085 -1.187127  0.371938    Semarang
9 -1.466572 -0.431312  0.035870 -0.307462    Denpasar

In [47]:
df1 = df[df['W']>0]
df1

          W         X         Y         Z        city
3  1.582947 -0.634168 -0.476795 -1.758901       Medan
4  0.354699  0.205733  1.064277  0.321967       Jogja
5  1.062526 -0.328039 -0.091156  0.373162     Lampung
6  0.379371  0.877800 -0.828435  0.010890  Balikpapan
7  1.570932 -0.300051 -0.148241  0.212808    Makassar
8  0.146590  1.377085 -1.187127  0.371938    Semarang

In [48]:
df1.reset_index()

   index         W         X         Y         Z        city
0      3  1.582947 -0.634168 -0.476795 -1.758901       Medan
1      4  0.354699  0.205733  1.064277  0.321967       Jogja
2      5  1.062526 -0.328039 -0.091156  0.373162     Lampung
3      6  0.379371  0.877800 -0.828435  0.010890  Balikpapan
4      7  1.570932 -0.300051 -0.148241  0.212808    Makassar
5      8  0.146590  1.377085 -1.187127  0.371938    Semarang

In [49]:
df1

          W         X         Y         Z        city
3  1.582947 -0.634168 -0.476795 -1.758901       Medan
4  0.354699  0.205733  1.064277  0.321967       Jogja
5  1.062526 -0.328039 -0.091156  0.373162     Lampung
6  0.379371  0.877800 -0.828435  0.010890  Balikpapan
7  1.570932 -0.300051 -0.148241  0.212808    Makassar
8  0.146590  1.377085 -1.187127  0.371938    Semarang

In [50]:
df1.reset_index(inplace=True)
df1

   index         W         X         Y         Z        city
0      3  1.582947 -0.634168 -0.476795 -1.758901       Medan
1      4  0.354699  0.205733  1.064277  0.321967       Jogja
2      5  1.062526 -0.328039 -0.091156  0.373162     Lampung
3      6  0.379371  0.877800 -0.828435  0.010890  Balikpapan
4      7  1.570932 -0.300051 -0.148241  0.212808    Makassar
5      8  0.146590  1.377085 -1.187127  0.371938    Semarang

In [58]:
df.set_index('city', inplace=True)
df

                   W         X         Y         Z
city
Jakarta    -1.076477 -0.570194 -0.983457  0.695465
Bandung    -1.011685  0.287847  0.353124  1.609088
Surabaya   -0.061852  0.407979  2.675069  0.139342
Medan       1.582947 -0.634168 -0.476795 -1.758901
Jogja       0.354699  0.205733  1.064277  0.321967
Lampung     1.062526 -0.328039 -0.091156  0.373162
Balikpapan  0.379371  0.877800 -0.828435  0.010890
Makassar    1.570932 -0.300051 -0.148241  0.212808
Semarang    0.146590  1.377085 -1.187127  0.371938
Denpasar   -1.466572 -0.431312  0.035870 -0.307462

In [59]:
df.loc['Jakarta']

W   -1.076477
X   -0.570194
Y   -0.983457
Z    0.695465
Name: Jakarta, dtype: float64

## Sorting

In [61]:
df

                   W         X         Y         Z
city
Jakarta    -1.076477 -0.570194 -0.983457  0.695465
Bandung    -1.011685  0.287847  0.353124  1.609088
Surabaya   -0.061852  0.407979  2.675069  0.139342
Medan       1.582947 -0.634168 -0.476795 -1.758901
Jogja       0.354699  0.205733  1.064277  0.321967
Lampung     1.062526 -0.328039 -0.091156  0.373162
Balikpapan  0.379371  0.877800 -0.828435  0.010890
Makassar    1.570932 -0.300051 -0.148241  0.212808
Semarang    0.146590  1.377085 -1.187127  0.371938
Denpasar   -1.466572 -0.431312  0.035870 -0.307462

In [63]:
df1 = df.sort_values('W', ascending=False)
df1

                   W         X         Y         Z
city
Medan       1.582947 -0.634168 -0.476795 -1.758901
Makassar    1.570932 -0.300051 -0.148241  0.212808
Lampung     1.062526 -0.328039 -0.091156  0.373162
Balikpapan  0.379371  0.877800 -0.828435  0.010890
Jogja       0.354699  0.205733  1.064277  0.321967
Semarang    0.146590  1.377085 -1.187127  0.371938
Surabaya   -0.061852  0.407979  2.675069  0.139342
Bandung    -1.011685  0.287847  0.353124  1.609088
Jakarta    -1.076477 -0.570194 -0.983457  0.695465
Denpasar   -1.466572 -0.431312  0.035870 -0.307462

In [64]:
df2 = df.sort_values(by=['W','X'], ascending=True)
df2

                   W         X         Y         Z
city
Denpasar   -1.466572 -0.431312  0.035870 -0.307462
Jakarta    -1.076477 -0.570194 -0.983457  0.695465
Bandung    -1.011685  0.287847  0.353124  1.609088
Surabaya   -0.061852  0.407979  2.675069  0.139342
Semarang    0.146590  1.377085 -1.187127  0.371938
Jogja       0.354699  0.205733  1.064277  0.321967
Balikpapan  0.379371  0.877800 -0.828435  0.010890
Lampung     1.062526 -0.328039 -0.091156  0.373162
Makassar    1.570932 -0.300051 -0.148241  0.212808
Medan       1.582947 -0.634168 -0.476795 -1.758901

In [66]:
df3 = df.sort_index()
df3

                   W         X         Y         Z
city
Balikpapan  0.379371  0.877800 -0.828435  0.010890
Bandung    -1.011685  0.287847  0.353124  1.609088
Denpasar   -1.466572 -0.431312  0.035870 -0.307462
Jakarta    -1.076477 -0.570194 -0.983457  0.695465
Jogja       0.354699  0.205733  1.064277  0.321967
Lampung     1.062526 -0.328039 -0.091156  0.373162
Makassar    1.570932 -0.300051 -0.148241  0.212808
Medan       1.582947 -0.634168 -0.476795 -1.758901
Semarang    0.146590  1.377085 -1.187127  0.371938
Surabaya   -0.061852  0.407979  2.675069  0.139342