# Pandas Operation

Data source : https://www.kaggle.com/datasets/amar5693/screen-time-sleep-and-stress-analysis-dataset/data

In [1]:
data_path = '/content/drive/MyDrive/JCAIEAH-003/Notes and Hands On/day-12/Smartphone_Usage_Productivity_Dataset_50000.csv'

In [2]:
import pandas as pd

# read csv
df = pd.read_csv(data_path)

In [3]:
df.head()

,User_ID,Age,Gender,Occupation,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours
0,U1,58,Male,Professional,Android,1.3,6.7,6,8.8,4,42,1,8.7
1,U2,25,Male,Professional,Android,1.2,1.5,5,6.4,1,51,3,5.1
2,U3,19,Male,Student,iOS,5.3,5.7,5,9.0,4,14,5,6.3
3,U4,35,Female,Business Owner,iOS,5.8,2.5,2,5.7,3,36,6,12.8
4,U5,33,Male,Freelancer,Android,7.9,1.3,4,5.7,3,37,5,9.9

In [4]:
# listing all columns
df.columns

Index(['User_ID', 'Age', 'Gender', 'Occupation', 'Device_Type',
       'Daily_Phone_Hours', 'Social_Media_Hours', 'Work_Productivity_Score',
       'Sleep_Hours', 'Stress_Level', 'App_Usage_Count',
       'Caffeine_Intake_Cups', 'Weekend_Screen_Time_Hours'],
      dtype='object')

In [5]:
# df info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   User_ID                    50000 non-null  object
 1   Age                        50000 non-null  int64
 2   Gender                     50000 non-null  object
 3   Occupation                 50000 non-null  object
 4   Device_Type                50000 non-null  object
 5   Daily_Phone_Hours          50000 non-null  float64
 6   Social_Media_Hours         50000 non-null  float64
 7   Work_Productivity_Score    50000 non-null  int64
 8   Sleep_Hours                50000 non-null  float64
 9   Stress_Level               50000 non-null  int64
 10  App_Usage_Count            50000 non-null  int64
 11  Caffeine_Intake_Cups       50000 non-null  int64
 12  Weekend_Screen_Time_Hours  50000 non-null  float64
dtypes: float64(4), int64(5), object(4)
memory usage: 5.0+ MB

In [9]:
# create new columns about average monthly phone hour
df["Monthly_Phone_Hours"] = df["Daily_Phone_Hours"].apply(lambda x : x*30)

In [10]:
df.head()

,User_ID,Age,Gender,Occupation,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours,Monthly_Phone_Hours
0,U1,58,Male,Professional,Android,1.3,6.7,6,8.8,4,42,1,8.7,39.0
1,U2,25,Male,Professional,Android,1.2,1.5,5,6.4,1,51,3,5.1,36.0
2,U3,19,Male,Student,iOS,5.3,5.7,5,9.0,4,14,5,6.3,159.0
3,U4,35,Female,Business Owner,iOS,5.8,2.5,2,5.7,3,36,6,12.8,174.0
4,U5,33,Male,Freelancer,Android,7.9,1.3,4,5.7,3,37,5,9.9,237.0

In [11]:
# implementing apply function in df

def det_age_category(age):
  if age < 25:
    category = "Young Adult"
  elif age <= 40:
    category = "Adult"
  else:
    category = "Senior Adult"
  return category

df["Age_Category"] = df["Age"].apply(det_age_category)

In [12]:
df.head()

,User_ID,Age,Gender,Occupation,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours,Monthly_Phone_Hours,Age_Category
0,U1,58,Male,Professional,Android,1.3,6.7,6,8.8,4,42,1,8.7,39.0,Senior Adult
1,U2,25,Male,Professional,Android,1.2,1.5,5,6.4,1,51,3,5.1,36.0,Adult
2,U3,19,Male,Student,iOS,5.3,5.7,5,9.0,4,14,5,6.3,159.0,Young Adult
3,U4,35,Female,Business Owner,iOS,5.8,2.5,2,5.7,3,36,6,12.8,174.0,Adult
4,U5,33,Male,Freelancer,Android,7.9,1.3,4,5.7,3,37,5,9.9,237.0,Adult

In [13]:
df[['Age', 'Age_Category']]

       Age  Age_Category
0       58  Senior Adult
1       25         Adult
2       19   Young Adult
3       35         Adult
4       33         Adult
...    ...           ...
49995   44  Senior Adult
49996   42  Senior Adult
49997   27         Adult
49998   41  Senior Adult
49999   46  Senior Adult

[50000 rows x 2 columns]

In [16]:
# create new columns differencing phone hour with sleep hout
df["Phone_vs_Sleep_Hours"] = df["Daily_Phone_Hours"] - df["Sleep_Hours"]

In [17]:
df.head()

,User_ID,Age,Gender,Occupation,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours,Monthly_Phone_Hours,Age_Category,Phone_vs_Sleep_Hours
0,U1,58,Male,Professional,Android,1.3,6.7,6,8.8,4,42,1,8.7,39.0,Senior Adult,-7.5
1,U2,25,Male,Professional,Android,1.2,1.5,5,6.4,1,51,3,5.1,36.0,Adult,-5.2
2,U3,19,Male,Student,iOS,5.3,5.7,5,9.0,4,14,5,6.3,159.0,Young Adult,-3.7
3,U4,35,Female,Business Owner,iOS,5.8,2.5,2,5.7,3,36,6,12.8,174.0,Adult,0.1
4,U5,33,Male,Freelancer,Android,7.9,1.3,4,5.7,3,37,5,9.9,237.0,Adult,2.2

In [19]:
df[['Daily_Phone_Hours', 'Sleep_Hours', 'Phone_vs_Sleep_Hours']]

       Daily_Phone_Hours  Sleep_Hours  Phone_vs_Sleep_Hours
0                    1.3          8.8                  -7.5
1                    1.2          6.4                  -5.2
2                    5.3          9.0                  -3.7
3                    5.8          5.7                   0.1
4                    7.9          5.7                   2.2
...                  ...          ...                   ...
49995                5.9          6.6                  -0.7
49996                2.9          6.3                  -3.4
49997                1.4          6.7                  -5.3
49998                8.9          5.5                   3.4
49999                8.8          5.4                   3.4

[50000 rows x 3 columns]

In [39]:
# select some columns from df
df1 = df[['Age_Category', 'Gender', 'Occupation', 'Daily_Phone_Hours']]
df1.head()

   Age_Category  Gender      Occupation  Daily_Phone_Hours
0  Senior Adult    Male    Professional                1.3
1         Adult    Male    Professional                1.2
2   Young Adult    Male         Student                5.3
3         Adult  Female  Business Owner                5.8
4         Adult    Male      Freelancer                7.9

In [44]:
pivot_table_df1 = df1.pivot_table(index=['Age_Category', 'Occupation'], columns='Gender', aggfunc='median', values='Daily_Phone_Hours')
display(pivot_table_df1)

Gender                       Female  Male  Other
Age_Category Occupation
Adult        Business Owner     6.7   6.7    6.5
             Freelancer         6.5   6.6    6.3
             Professional       6.4   6.4    6.5
             Student            6.6   6.3    6.7
Senior Adult Business Owner     6.7   6.5    6.7
             Freelancer         6.4   6.5    6.5
             Professional       6.6   6.7    6.6
             Student            6.5   6.5    6.6
Young Adult  Business Owner     6.4   6.8    6.2
             Freelancer         6.8   6.6    6.7
             Professional       6.4   6.5    6.3
             Student            6.3   6.1    6.5

In [53]:
pivot_table_df1.reset_index(inplace=True)
pivot_table_df1

Gender  Age_Category      Occupation  Female  Male  Other
0              Adult  Business Owner     6.7   6.7    6.5
1              Adult      Freelancer     6.5   6.6    6.3
2              Adult    Professional     6.4   6.4    6.5
3              Adult         Student     6.6   6.3    6.7
4       Senior Adult  Business Owner     6.7   6.5    6.7
5       Senior Adult      Freelancer     6.4   6.5    6.5
6       Senior Adult    Professional     6.6   6.7    6.6
7       Senior Adult         Student     6.5   6.5    6.6
8        Young Adult  Business Owner     6.4   6.8    6.2
9        Young Adult      Freelancer     6.8   6.6    6.7
10       Young Adult    Professional     6.4   6.5    6.3
11       Young Adult         Student     6.3   6.1    6.5

In [54]:
pivot_table_df1.to_excel('/content/drive/MyDrive/JCAIEAH-003/Notes and Hands On/day-12/pivot_table_df1.xlsx', index=False)

In [56]:
df_new = pd.read_html('https://docs.google.com/spreadsheets/d/1BK_3liQCS_TDp0NnO4ym-mitzYHczj5u/edit?usp=sharing&ouid=104310638236272865698&rtpof=true&sd=true')
df_new

[    Unnamed: 0             A               B       C     D      E   F   G   H  \
 0            1  Age_Category      Occupation  Female  Male  Other NaN NaN NaN
 1            2         Adult  Business Owner      67    67     65 NaN NaN NaN
 2            3         Adult      Freelancer      65    66     63 NaN NaN NaN
 3            4         Adult    Professional      64    64     65 NaN NaN NaN
 4            5         Adult         Student      66    63     67 NaN NaN NaN
 ..         ...           ...             ...     ...   ...    ...  ..  ..  ..
 95          96           NaN             NaN     NaN   NaN    NaN NaN NaN NaN
 96          97           NaN             NaN     NaN   NaN    NaN NaN NaN NaN
 97          98           NaN             NaN     NaN   NaN    NaN NaN NaN NaN
 98          99           NaN             NaN     NaN   NaN    NaN NaN NaN NaN
 99         100           NaN             NaN     NaN   NaN    NaN NaN NaN NaN

      I  ...   Q   R   S   T   U   V   W   X   Y   Z
 0  NaN  ... NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
 1  NaN  ... NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
 2  NaN  ... NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
 3  NaN  ... NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
 4  NaN  ... NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
 ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
 95 NaN  ... NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
 96 NaN  ... NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
 97 NaN  ... NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
 98 NaN  ... NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
 99 NaN  ... NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN

 [100 rows x 27 columns],
     0   1       2   3   4
 0 NaN NaN  Sheet1 NaN NaN]